import sqlite3
import re
import os

db_path = "salesmis.db"
out_path = "../oracle_backup.sql"

if not os.path.exists(db_path):
    print(f"Error: Database file {db_path} not found.")
    exit(1)

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Get table names
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';")
tables = [row[0] for row in cursor.fetchall()]

oracle_ddl = """-- Oracle Database Backup & Migration Script
-- Generated from Sales MIS PostgreSQL/SQLite Database

-- -------------------------------------------------------------
-- Clean Up Existing Tables (Drop order matters for foreign keys)
-- -------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE inventory_movements CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE order_items CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- -------------------------------------------------------------
-- DDL - Tables Creation (Oracle Dialect)
-- -------------------------------------------------------------

CREATE TABLE users (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    full_name VARCHAR2(120) NOT NULL,
    hashed_password VARCHAR2(255) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    is_admin NUMBER(1) DEFAULT 0 CHECK (is_admin IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR2(30) NOT NULL UNIQUE,
    sku VARCHAR2(80) NOT NULL UNIQUE,
    name VARCHAR2(160) NOT NULL,
    category VARCHAR2(100) DEFAULT 'General',
    price NUMBER(12, 2) NOT NULL,
    stock NUMBER(10) DEFAULT 0 NOT NULL,
    reorder_level NUMBER(10) DEFAULT 15 NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR2(30) NOT NULL UNIQUE,
    name VARCHAR2(120) NOT NULL,
    company VARCHAR2(160),
    email VARCHAR2(255) NOT NULL UNIQUE,
    phone VARCHAR2(40),
    segment VARCHAR2(40) DEFAULT 'Active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR2(40) NOT NULL UNIQUE,
    customer_id NUMBER(10) NOT NULL,
    channel VARCHAR2(60) DEFAULT 'Online Store',
    status VARCHAR2(30) DEFAULT 'Pending',
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total NUMBER(14, 2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE order_items (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER(10) NOT NULL,
    product_id NUMBER(10) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    unit_price NUMBER(12, 2) NOT NULL,
    line_total NUMBER(14, 2) NOT NULL,
    CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE inventory_movements (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(10) NOT NULL,
    movement_type VARCHAR2(30) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    note VARCHAR2(255),
    created_by NUMBER(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_movements_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_movements_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- DML - Data Ingestion (Insert statements in Dependency Order)
-- -------------------------------------------------------------
"""

insertion_order = ["users", "products", "customers", "orders", "order_items", "inventory_movements"]

with open(out_path, "w", encoding="utf-8") as f:
    f.write(oracle_ddl)
    f.write("\n")
    
    for table in insertion_order:
        f.write(f"-- -------------------------------------------------------------\n")
        f.write(f"-- Data for table {table}\n")
        f.write(f"-- -------------------------------------------------------------\n")
        cursor.execute(f"PRAGMA table_info({table})")
        columns_info = cursor.fetchall()
        cols = [c[1] for c in columns_info]
        
        cursor.execute(f"SELECT * FROM {table}")
        rows = cursor.fetchall()
        
        for row in rows:
            val_strs = []
            for col_name, val in zip(cols, row):
                if val is None:
                    val_strs.append("NULL")
                elif isinstance(val, bool):
                    val_strs.append("1" if val else "0")
                elif isinstance(val, (int, float)):
                    # Special check: boolean column represented as integer (e.g., is_active, is_admin)
                    val_strs.append(str(val))
                else:
                    # String or DateTime
                    val_str = str(val).replace("'", "''") # Escape single quotes
                    
                    # If it looks like a datetime, use Oracle's TO_TIMESTAMP
                    if re.match(r'^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}', val_str):
                        clean_dt = val_str.replace("T", " ")[:19]
                        val_strs.append(f"TO_TIMESTAMP('{clean_dt}', 'YYYY-MM-DD HH24:MI:SS')")
                    else:
                        val_strs.append(f"'{val_str}'")
            
            cols_joined = ", ".join(cols)
            vals_joined = ", ".join(val_strs)
            f.write(f"INSERT INTO {table} ({cols_joined}) VALUES ({vals_joined});\n")
        f.write("\n")
    
    f.write("COMMIT;\n")

print(f"Successfully generated Oracle Database compatible SQL script: {os.path.abspath(out_path)}")
conn.close()
