import sqlite3
import re
import os

db_path = "salesmis.db"
out_path = "../oracle_backup.sql"

if not os.path.exists(db_path):
    print(f"Error: Database file {db_path} not found.")
    exit(1)

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Get table names
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';")
tables = [row[0] for row in cursor.fetchall()]

oracle_ddl = """-- Oracle Database Backup & Migration Script
-- Generated from Sales MIS PostgreSQL/SQLite Database
-- Optimized for large enterprise datasets (future-proof & clean)

-- -------------------------------------------------------------
-- Clean Up Existing Database Objects (Prevent conflicts)
-- -------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW NumberClientOrdered';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW TotalSaleAmount';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW TotalAmountByOrderNo';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW v_product_performance';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW v_monthly_sales_summary';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW v_low_stock_alerts';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE inventory_movements CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE order_items CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE employees CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- -------------------------------------------------------------
-- DDL - Tables Creation (Oracle Dialect with Timezone Safety)
-- -------------------------------------------------------------

CREATE TABLE users (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    full_name VARCHAR2(120) NOT NULL,
    hashed_password VARCHAR2(255) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    is_admin NUMBER(1) DEFAULT 0 CHECK (is_admin IN (0, 1)),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR2(30) NOT NULL UNIQUE,
    sku VARCHAR2(80) NOT NULL UNIQUE,
    name VARCHAR2(160) NOT NULL,
    category VARCHAR2(100) DEFAULT 'General',
    price NUMBER(12, 2) NOT NULL,
    stock NUMBER(10) DEFAULT 0 NOT NULL,
    reorder_level NUMBER(10) DEFAULT 15 NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    product_type VARCHAR2(100) DEFAULT 'Accessory',
    unit_measure VARCHAR2(40) DEFAULT 'Piece',
    cost_price NUMBER(12, 2) DEFAULT 0.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR2(30) NOT NULL UNIQUE,
    name VARCHAR2(120) NOT NULL,
    company VARCHAR2(160),
    email VARCHAR2(255) NOT NULL UNIQUE,
    phone VARCHAR2(40),
    segment VARCHAR2(40) DEFAULT 'Active',
    address VARCHAR2(255),
    city VARCHAR2(100),
    client_type VARCHAR2(40) DEFAULT 'Normal',
    discount NUMBER(5, 2) DEFAULT 0.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employees (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(120) NOT NULL,
    gender VARCHAR2(10),
    birth_date VARCHAR2(30),
    job VARCHAR2(100),
    address VARCHAR2(255),
    phone VARCHAR2(40),
    salary NUMBER(12, 2) DEFAULT 0.0,
    remarks VARCHAR2(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR2(40) NOT NULL UNIQUE,
    customer_id NUMBER(10) NOT NULL,
    channel VARCHAR2(60) DEFAULT 'Online Store',
    status VARCHAR2(30) DEFAULT 'Pending',
    ordered_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total NUMBER(14, 2) DEFAULT 0,
    employee_id NUMBER(10),
    delivery_type VARCHAR2(20) DEFAULT 'F',
    delivery_date VARCHAR2(30),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_orders_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE TABLE order_items (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER(10) NOT NULL,
    product_id NUMBER(10) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    unit_price NUMBER(12, 2) NOT NULL,
    line_total NUMBER(14, 2) NOT NULL,
    CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE inventory_movements (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(10) NOT NULL,
    movement_type VARCHAR2(30) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    note VARCHAR2(255),
    created_by NUMBER(10),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_movements_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_movements_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- Indexes for Big Database Performance & Join Optimization
-- -------------------------------------------------------------
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_employee_id ON orders(employee_id);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);
CREATE INDEX idx_inv_movements_product_id ON inventory_movements(product_id);
CREATE INDEX idx_inv_movements_created_by ON inventory_movements(created_by);

-- -------------------------------------------------------------
-- Triggers for Automated updated_at Field Updates
-- -------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
   :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
BEGIN
   :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW
BEGIN
   :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_employees_updated_at
BEFORE UPDATE ON employees
FOR EACH ROW
BEGIN
   :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
BEGIN
   :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- -------------------------------------------------------------
-- Analytical Database Views & Midterm Views
-- -------------------------------------------------------------
CREATE OR REPLACE VIEW v_low_stock_alerts AS
SELECT id, product_code, sku, name, stock, reorder_level
FROM products
WHERE is_active = 1 AND stock <= reorder_level;

CREATE OR REPLACE VIEW v_monthly_sales_summary AS
SELECT 
    TO_CHAR(ordered_at, 'YYYY-MM') AS sales_month,
    COUNT(id) AS total_orders,
    SUM(total) AS total_revenue,
    AVG(total) AS average_order_value
FROM orders
WHERE status != 'Cancelled'
GROUP BY TO_CHAR(ordered_at, 'YYYY-MM');

CREATE OR REPLACE VIEW v_product_performance AS
SELECT 
    p.id AS product_id,
    p.name AS product_name,
    p.sku,
    SUM(oi.quantity) AS units_sold,
    SUM(oi.line_total) AS total_revenue,
    DENSE_RANK() OVER (ORDER BY SUM(oi.quantity) DESC NULLS LAST) AS sales_rank
FROM products p
JOIN order_items oi ON p.id = oi.product_id
JOIN orders o ON o.id = oi.order_id
WHERE o.status != 'Cancelled'
GROUP BY p.id, p.name, p.sku;

CREATE OR REPLACE VIEW NumberClientOrdered AS
SELECT c.id as Client_no, c.name as ClientName, c.phone, COUNT(o.id) as NumberOrder
FROM customers c
JOIN orders o ON c.id = o.customer_id
GROUP BY c.id, c.name, c.phone;

CREATE OR REPLACE VIEW TotalSaleAmount AS
SELECT o.id as Order_No, o.ordered_at as Order_date, o.customer_id as Client_No, c.name as ClientName, p.product_code as Product_no, p.name as ProductName, od.quantity as Qty, od.unit_price as Price, od.line_total as Amount
FROM orders o
JOIN customers c ON o.customer_id = c.id
JOIN order_items od ON o.id = od.order_id
JOIN products p ON od.product_id = p.id;

CREATE OR REPLACE VIEW TotalAmountByOrderNo AS
SELECT o.id as Order_No, o.ordered_at as Order_date, o.customer_id as Client_No, c.name as ClientName, SUM(od.quantity * od.unit_price) as Amount, COUNT(od.product_id) as "Item#"
FROM orders o
JOIN customers c ON o.customer_id = c.id
JOIN order_items od ON o.id = od.order_id
GROUP BY o.id, o.ordered_at, o.customer_id, c.name;

-- -------------------------------------------------------------
-- DML - Data Ingestion (Insert statements in Dependency Order)
-- -------------------------------------------------------------
"""

insertion_order = ["users", "products", "customers", "employees", "orders", "order_items", "inventory_movements"]


with open(out_path, "w", encoding="utf-8") as f:
    f.write(oracle_ddl)
    f.write("\n")
    
    for table in insertion_order:
        f.write(f"-- -------------------------------------------------------------\n")
        f.write(f"-- Data for table {table}\n")
        f.write(f"-- -------------------------------------------------------------\n")
        cursor.execute(f"PRAGMA table_info({table})")
        columns_info = cursor.fetchall()
        cols = [c[1] for c in columns_info]
        
        cursor.execute(f"SELECT * FROM {table}")
        rows = cursor.fetchall()
        
        for row in rows:
            val_strs = []
            for col_name, val in zip(cols, row):
                if val is None:
                    val_strs.append("NULL")
                elif isinstance(val, bool):
                    val_strs.append("1" if val else "0")
                elif isinstance(val, (int, float)):
                    # Special check: boolean column represented as integer (e.g., is_active, is_admin)
                    val_strs.append(str(val))
                else:
                    # String or DateTime
                    val_str = str(val).replace("'", "''") # Escape single quotes
                    
                    # If it looks like a datetime, use Oracle's TO_TIMESTAMP
                    if re.match(r'^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}', val_str):
                        clean_dt = val_str.replace("T", " ")[:19]
                        val_strs.append(f"TO_TIMESTAMP('{clean_dt}', 'YYYY-MM-DD HH24:MI:SS')")
                    else:
                        val_strs.append(f"'{val_str}'")
            
            cols_joined = ", ".join(cols)
            vals_joined = ", ".join(val_strs)
            f.write(f"INSERT INTO {table} ({cols_joined}) VALUES ({vals_joined});\n")
        f.write("\n")
    
    f.write("COMMIT;\n")

print(f"Successfully generated Oracle Database compatible SQL script: {os.path.abspath(out_path)}")
conn.close()
